### PR TITLE
Box plot update

### PR DESCRIPTION
**Pull request by norawebbwilliams**
Adding correction for the box plot example on page 103.

### CODE REVIEW

**Comment by kosukeimai** [comment]
@norawebbwilliams Thanks.  Let's add a correct figure file in the errata - add a code that generates it directly in the markdown file so that we have a replacement when PUP prints out a new version.

**Comment by norawebbwilliams** [comment]
@kosukeimai -- I've added the remade boxplot figure with the correction. Look okay?

**Comment by kosukeimai** [comment]
It's 1.5 IQR from the third quartile rather than from the median.  Can you check to make sure that the description in QSStidy is correct?

**Comment by norawebbwilliams** [comment]
Oh goodness, of course... Seems like both braces were shifted down. I'll take a look. Thanks for the catch!!!

**Comment by norawebbwilliams** [comment]
The description in QSStidy is correct and I've updated the figure (I hope correctly this time, but let me know!).

**Pull request merged**
