### PR TITLE
Check the R scripts inside the Rmd files are free of errors, at the time of submitting.

### PR DESCRIPTION
**Pull request by HJ08003**

### CODE REVIEW

**Comment by kosukeimai** [comment]
@HJ08003 Instead of writing the script in `.travis.yml` Can you create a file called `test.R` and then have travis run that test script?  That's a cleaner implementation.

**Comment by HJ08003** [comment]
The test.R version is in, and passed travis-ci check.

**Comment by kosukeimai** [comment]
@HJ08003 Can we do this without `DESCRIPTION` file?  Why not install these packages at the beginning of `test.R`?  Also, why do we need the `vignettes` directory?

**Comment by HJ08003** [comment]
I added the DESCRIPTION file after this failed built at travis-ci

R session information

$ Rscript -e 'sessionInfo()'

R version 3.4.1 (2017-01-27)

Platform: x86_64-pc-linux-gnu (64-bit)

Running under: Ubuntu 14.04.5 LTS

Matrix products: default

BLAS: /home/travis/R-bin/lib/R/lib/libRblas.so

LAPACK: /home/travis/R-bin/lib/R/lib/libRlapack.so

locale:

 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C

 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8

 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8

 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C

 [9] LC_ADDRESS=C               LC_TELEPHONE=C

[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:

[1] stats     graphics  grDevices utils     datasets  base

loaded via a namespace (and not attached):

[1] compiler_3.4.1

No DESCRIPTION file found, user must supply their own install and script steps

Without the DESCRIPTION file, R and all required packages are not installed at travis-ci automatically. These will be needed in .travis.yml:

   - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
   - chmod 755 ./travis-tool.sh
   - ./travis-tool.sh bootstrap
   - echo "Install the dependency R packages used in the test scripts ..."
   - ./travis-tool.sh install_r foreign
   - ./travis-tool.sh install_r lintr
   - Rscript -e 'library(lintr); library(foreign)'

**Pull request merged**
