### PR TITLE
RtoRmd

### PR DESCRIPTION
**Pull request by tylersimko**
How does this look? I copied your format from Ch. 5 for Ch. 1. If this is okay I'll do the rest of them before we merge it.

### CODE REVIEW

**Comment by kosukeimai** [comment]
Looks great except that when you are not actually running the code, let's use `eval = FALSE` rather than commenting them out with `#`

**Comment by tylersimko** [comment]
Here's everything, let me know how it looks.

**Comment by kosukeimai** [comment]
Thanks.  Can you remove the graphical `par()` parameter, e.g., `par(cex = 1.5)`, so that the plots look reasonable?  For example, you've left them out in the Measurement chapter.  It would be good to check the other chapters too.  Thanks.

**Comment by tylersimko** [comment]
Gone!

**Comment by kosukeimai** [comment]
Looks great. Thanks!

**Pull request merged**
