### PR TITLE
Causality Code

### PR DESCRIPTION
**Pull request by tylersimko**
Here's chapter 2, everything works as is.

### CODE REVIEW

**Comment by kosukeimai** [comment]
Can you add README.md like I did in Chapter 1?

**Comment by tylersimko** [comment]
How's this? I copied the format exactly. I couldn't find any mentions in the book for two of the files: `basque.csv` and `boston.csv`, so I didn't add them to the `README` yet. Are they for exercises?

**Comment by kosukeimai** [comment]
I think you can remove `basque.csv` and `boston.csv` as they are additional exercises.

**Comment by kosukeimai** [comment]
Also, the file name should be `causality.R` rather than `intro.R`.  Can you make sure that the links to the data sets work properly?

**Comment by tylersimko** [comment]
Okay, script is fixed. Do you know how to check if the links work before it's merged?

**Comment by kosukeimai** [comment]
you will need to do `[resume.csv](resume.csv)` etc.

**Comment by tylersimko** [comment]
Got it - thanks! Fixed.

**Pull request merged**
